name: Build kernel deb packages
on: push

jobs:
  build:
    name: Build kernel
    runs-on: ubuntu-latest
    container: debian:buster
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: bash build_action.sh

      - name: Artifact-deb
        uses: actions/upload-artifact@v2
        with:
          name: artifact-deb
          path: ${{ github.workspace }}/artifact-deb/

      - name: Artifact-env
        uses: actions/upload-artifact@v2
        with:
          name: artifact-env
          path: ${{ github.workspace }}/artifact-env/
